### ISSUE TITLE
need help to remap ESP32-s3 N16R8

### ISSUE THREAD

**Issue by bereza0007** [thelastoutpostworkshop/ESP32ManyRoundScreenTest#1]
hello, if you can help me to remap for ESP32 s3 wroom1 n16r8, really appreciated, watched all your videos, cant find solution. I made some .h videos but cant fit to 3mb flash. 
![esp32-s3 wroom1 n16r8 - 1](https://github.com/thelastoutpostworkshop/ESP32ManyRoundScreenTest/assets/46094322/d47b2d3c-0126-4c78-9911-16ab39423555)
![esp32-s3 wroom1 n16r8](https://github.com/thelastoutpostworkshop/ESP32ManyRoundScreenTest/assets/46094322/a78a9f51-8cba-45c6-82f0-11a32e9712a1)

**Comment by thelastoutpostworkshop** [comment]
There is a limit on how many .h you can load into program memory, program memory is limited.

**Comment by bereza0007** [comment]
Sorry, issue not with .h
Problem with ESP32 n16r8
Some GPOI pins from your video not matching with my ESP32 n16r8
How to reassigned pins ?

**Comment by bereza0007** [comment]
i guess said wrong about remap. what i mean pins, sorry

**Comment by bereza0007** [comment]
![yt](https://github.com/thelastoutpostworkshop/ESP32ManyRoundScreenTest/assets/46094322/3cd60d99-fcd4-49cd-a9af-b3c5976344d4)

**Comment by thelastoutpostworkshop** [comment]
Based on the pinout of your board, in Setup46_GC9A01_ESP32,h would try these :
TFT_MOSI 4
TFT_SCLK 5
TFT_DC 6 
TFT_RST 7 

For the CS of the screens you can use any of these : 15,16,17,18,8, 9, 10,11,12,13

**Comment by bereza0007** [comment]
Hello, I think you talking about  Setup46_GC9A01_ESP32,h in your "Master DALL-E Image Generation with ESP32!" setup, correct?

I am referring to your "Can the ESP32 Handle 6 animated GIFs on 6 Screens ?" video, i cant locate Setup46_GC9A01_ESP32,h

i just need to figure out how to define BUS pins to work in that code for esp32 n16r2 chip, ,BTW,  its the same DEV Board u used for Dalle video.

Thanks you,

**Comment by thelastoutpostworkshop** [comment]
if you have the TFT_eSPI library installed, you should be able to navigate to TFT_eSPI.h, then to User_SetupSelect.h.  
In that header file, you will find this line
// #include <User_Setups/Setup46_GC9A01_ESP32.h>      // Setup file for ESP32 and GC9A01 SPI bus TFT  240x240
You have to uncomment it.  
it is in this header file that you defined SPI pins, I am not sure what you mean by BUS pins.
